### ISSUE TITLE
Create `active` parameter to differentiate between active Vs passive accessibility

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/accessibility#20]
Create a boolean `active` parameter in accessibility functions that will allow users to calculate active acessibility when `active = TRUE` (the default) and passive accessibility when `active = FALSE`.

**Comment by dhersz** [comment]
As of https://github.com/ipeaGIT/accessibility/commit/e4f239aed6805aee02dc965bf0f0f7d52026143d all accessibility functions (but `floating_catchment_area()`, as it doesn't really seem to make much sense to me) include the `active` parameter
