### ISSUE TITLE
Major change in input data to separate travel matrix from landuse data

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/accessibility#22]
Accessibility functions in the package currently have only one input data parameter called `data`, which receives a travel time matrix in long format with additional columns indicating population in the origins and activities in the destinations. This strategy has a few downsides. Perhaps the most important of these downsides is that this stratey requires an additional step for users to manually merge travel matrix and landuse data, which can be quite memory intensive if not done properly. After long discussion, @dhersz and I decided (he convinced me, really) to make a major change in input data to separate travel matrix from landuse data inputs.

This means replacing the `data` parameter with two new parameters, which could be called (a suggestion here) `travel_matrix` and `landuse_data`.

Moreover, the `travel_matrix`  would necessarily have the columns `from_id` and `to_id`, and the `landuse_data` would necessarily have the column `id` to identify the id of origins and destinations.

**Comment by dhersz** [comment]
As of https://github.com/ipeaGIT/accessibility/commit/e4f239aed6805aee02dc965bf0f0f7d52026143d all accessibility functions take `travel_matrix` and `land_use_data` as inputs.
