### ISSUE TITLE
Questions about `time_to_closest()`

### ISSUE THREAD

**Issue by dhersz** [ipeaGIT/accessibility#23]
1. Should it become `cost_to_closest()`? `minimum_cost()`? `minimum_travel_cost()`?
2. Should it return more than 1 id if in the destination column if more than 1 matches the minimum cost?
3. Should destination be a list-column? If not, how to deal with ids that have the `;` character?

**Comment by rafapereirabr** [comment]
There are very good points.

1. I think `cost_to_closest()` is more intuitive.
2. I haven't thought about that possibility, but yes. If there are two or more destinations that match the mininum travel cost, then we should probably return all of their ids.
3. This is a tricky one. I understantand the current implementation could create some confusion if there ids with `;`. This is pretty rare, though. On the other hand, using a list-column format for the `destination` column can be a problem for users who would like to save the output in `.csv`. Not sure what would be the best way to go around this problem.

**Comment by dhersz** [comment]
>     3. This is a tricky one. I understantand the current implementation could create some confusion if there ids with `;`. This is pretty rare, though. On the other hand, using a list-column format for the `destination` column can be a problem for users who would like to save the output in `.csv`. Not sure what would be the best way to go around this problem.

This is indeed tricky. Here's how data.table handles list columns:

```r
library(data.table)

df <- data.table(
  a = c(1, 2),
  b = list(c("ola", "oie"), "tchau")
)
df
#>    a       b
#> 1: 1 ola,oie
#> 2: 2   tchau

tmpfile <- tempfile(fileext = ".csv")
fwrite(df, tmpfile)

fread(tmpfile)
#>    a       b
#> 1: 1 ola|oie
#> 2: 2   tchau
```

Actual file content:

```r
a,b
1,ola|oie
2,tchau
```

**Comment by dhersz** [comment]
The function is now called `cost_to_closest()`.

As of https://github.com/ipeaGIT/accessibility/commit/3eed7359138b0248eee85aa3949e263ccb9e57be it no longer returns the destinations/origins in which the N lowest cost opportunities were located at.

As mentioned before, when n = 1 we could have the situation where many destinations were equally far apart. The "obvious" answer here would be to return all of them.

But that could also happen when n > 1, and the answer wouldn't be as trivial. In such case, the function would return all the destinations that would be required to reach the N lowest cost opportunities. Let's say we had an n of 5, and had 15 destinations equally costly to reach that had 1 opportunity each. Should the function return all 15 destinations in the result (which would sum up to 15 opportunities) or only the "first" 5 (in alphabetical order, for example)? It doesn't seem to make sense to return some destinations and not others, but at the same time returning 15 different destinations when we wanted to reach only 5 opportunities looked strange too.

Until we decide how the result should actually look like we decided to remove this column.
