### ISSUE TITLE
Add dual accessibility metric, by Cui & Levinson (2020)

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/accessibility#24]
Add a function to calculate dual accessibility as discussed in Cui & Levinson (2020) and which measures "time required to reach a given number of opportunities".

- Cui, M., & Levinson, D. (2020). **Primal and dual access**. [Geographical Analysis, 52(3), 452-474](https://onlinelibrary.wiley.com/doi/abs/10.1111/gean.12220).

this could be implemented in future versions, not necessarily v1.0.0

**Comment by dhersz** [comment]
How is that any different from `cost_to_closest()`?

**Comment by rafapereirabr** [comment]
From the paper. "The dual of accessibility, measuring the time required to reach a given number of opportunities". Indeed, this is exactly the same as `cost_to_closest()`.
