### ISSUE TITLE
Add balancing time metric, by Barboza et al (2021)

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/accessibility#25]
Add a function to calculate balancing time accessibility as discussed in Barboza et al (2021) and which measures "travel time required from a given location to access the number of jobs equal to the population of the given location".

- Barboza, M. H., Carneiro, M. S., Falavigna, C., Luz, G., & Orrico, R. (2021). **Balancing time: Using a new accessibility measure in Rio de Janeiro**. [Journal of Transport Geography, 90, 102924](https://doi.org/10.1016/j.jtrangeo.2020.102924).

this could be implemented in future versions, not necessarily v1.0.0

**Comment by dhersz** [comment]
First draft here https://github.com/ipeaGIT/accessibility/commit/6676f87d5e71e091d299771683603c45c46f0232

**Comment by dhersz** [comment]
Done in https://github.com/ipeaGIT/accessibility/commit/0284e57ea711c4cbd3c113e108421ac3cbc8c832.
