### ISSUE TITLE
Add spatial_availability(), by  Soukhov et al (2023)

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/accessibility#28]
@soukhova has pointed out they have version of the function written with {dplyr} syntax [here](https://github.com/soukhova/Spatial-Availability-Measure/blob/main/Spatial-Availability-Paper/Spatial-Availability-Paper.Rmd#L83).

- Soukhov A, Páez A, Higgins CD, Mohamed M (2023) **Introducing spatial availability, a singly-constrained measure of competitive accessibility**. _PLoS ONE_ 18(1): e0278468. [https://doi.org/10.1371/journal.pone.0278468](https://doi.org/10.1371/journal.pone.0278468)

To include this function to the {accessibility} pacakge, we would need to:
- translate to {data.table} syntax and the code conventions used in the package
- double check if our results are consistent with the original code
- create a package function with basic documentation.

**Comment by dhersz** [comment]
Done in https://github.com/ipeaGIT/accessibility/commit/7dcc3f541d9c3b75aabd062188a6b91b4c6e22f4.
