### ISSUE TITLE
error :  could not find function "spatial_availability"

### ISSUE THREAD

**Issue by luisarmandog** [ipeaGIT/accessibility#32]
Hi, thank you very much for your contribution related to the accessibility package. However, when I run the example script, I encounter the following error: 

  -  decay_function = decay_exponential(decay_value = 0.1)

**Error in spatial_availability(travel_matrix, land_use_data, opportunity = "jobs",  : 
  could not find function "spatial_availability"**

I have already installed previous versions from CRAN and from Github, but the error still persists.

**Comment by rafapereirabr** [comment]
Hi @luisarmandog . Could you please try running the code below and pasting the error you get?

```
remotes::install_github("ipeaGIT/accessibility")

library(accessibility)

travel_matrix <- data.table::data.table(
  from_id = rep(c("A", "B", "C"), each = 3),
  to_id = as.character(rep(1:3, 3)),
  travel_time = c(15, 30, 100, 30, 15, 100, 100, 100, 15)
)

land_use_data <- data.table::data.table(
  id = c("A", "B", "C", "1", "2", "3"),
  population = c(50000, 150000, 10000, 0, 0, 0),
  jobs = c(0, 0, 0, 100000, 100000, 10000)
)

df <- spatial_availability(
  travel_matrix,
  land_use_data,
  opportunity = "jobs",
  travel_cost = "travel_time",
  demand = "population",
  decay_function = decay_exponential(decay_value = 0.1)
)

df
```

**Comment by dhersz** [comment]
The function is currently available only on the dev version of the package. Installing it with `remotes::install_github("ipeaGIT/accessibility")`, as Rafa pointed out, should be enough to use the function.
