### ISSUE TITLE
Gini returns NA for subset of data

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/accessibility#37]
Supose I only want to calculate the Gini coef. for the Black individuals in my study area. The intuitive step is to filter the `land_use` data set to keep only observations of Black population. However, this causes the `gini_index()` function to return `NA`.

### reprex
```
library(accessibility)

data_dir <- system.file("extdata", package = "accessibility")
travel_matrix <- readRDS(file.path(data_dir, "travel_matrix.rds"))
land_use_data <- readRDS(file.path(data_dir, "land_use_data.rds"))

# add race groups
land_use_data$race <- sample(c("W","B"), size = nrow(land_use_data), replace = T)

# calculate access
access <- cumulative_cutoff(
  travel_matrix,
  land_use_data,
  cutoff = 30,
  opportunity = "jobs",
  travel_cost = "travel_time"
)



# subset only blacks
blacks <- subset(land_use_data, race=='B')

# Gini
gini_index(
  access,
  sociodemographic_data = blacks,
  opportunity = "jobs",
  population = "population"
)
#>    gini_index
#> 1:         NA
```

**Comment by rafapereirabr** [comment]
It seems this problem also affects the `fgt_poverty()` function.

```
fgt_poverty(
  access,
  opportunity = "jobs",
  sociodemographic_data = blacks,
  population = "population",
  poverty_line = 95368
)
#>    FGT0 FGT1 FGT2
#> 1:   NA   NA   NA
```

**Comment by dhersz** [comment]
The problem happens when merging the accessibility and the sociodemographic datasets. Many of the ids present in the former cannot be found in the latter, which results in many NAs.

Honestly, to me the intuitive thing to do would be to subset the accessibility data to only include the desired cells there, not in the sociodemographic dataset. After all, we want to calculate the gini index of that specific accessibility distribution - if you need to calculate it for a subset of cells only, you need to change the distribution, not the auxiliary data (sociodemographic data, which is only used to weigh the estimates). 

Also, how would we be able to distinguish between explicitly leaving some cells out the in the land use dataset to calculate inequality for a few cells only (e.g. the case you mentioned) vs mistakenly leaving some cells out?

**Comment by rafapereirabr** [comment]
You say "the intuitive thing to do would be to subset the accessibility data to only include the desired cells there". However, in the example above, the filter is based on a socioeconomic variable in the populuation/land use data.

I agree we cannot know whether users make a concious decision of filtering some of observations in the land use dataset, or if they mistakenly leaving some cells out. There is only so much we can do protect users from making mistakes.

However, solving this issues would be pretty simple. We would simply need to filter the travel matrix before merging the data, like in the code below:

```
merge_by_reference <- function(data,
                               land_use_data,
                               opportunity,
                               left_df_idcol) {
  # when calculating active accessibility, we want the number of opportunities
  # in the destination. if passive, the number of opportunities in the origin

  right_df_idcol <- "id"

  join_vector <- right_df_idcol
  names(join_vector) <- left_df_idcol

  #### filter travel matrix #### 
  data <- subset(data, get(left_df_idcol) %in% land_use_data[, get(join_vector)])
  ######## 

  data[
    land_use_data,
    on = join_vector,
    eval(opportunity) := get(paste0("i.", ..opportunity))
  ]
}

```

**Comment by dhersz** [comment]
> You say "the intuitive thing to do would be to subset the accessibility data to only include the desired cells there". However, in the example above, the filter is based on a socioeconomic variable in the populuation/land use data.

Yeah, I know, I'm disagreeing with you here. In my opinion, if you want to calculate a different Gini Index/whatever metric you have to change the accessibility distribution so it only includes some specific cells, regardless of the chosen criteria to do so. In other words, I don't think that, given the same accessibility distribution, the result should change based on the presence or not of some specific cells in the sociodemographic data.

**Comment by rafapereirabr** [comment]
Sure, I agree that if someone wants to calculate a different Gini Index/whatever metric to a particular population group, the person needs to subset the accessibility estimates to keep those observations of interest (Black population in my example above).

The thing is, the way our inequality and poverty functions work, we "force" users to pass accessibility and population data in separate data frames. This is what makes things a bit complicated here.

**Comment by dhersz** [comment]
New warning message, similar to the other issue with NA accessibility values caused by the land use data.

```
R> gini_index( 
           access, 
           sociodemographic_data = blacks, 
           opportunity = "jobs", 
           population = "population" 
         )     
   gini_index
1:         NA
Warning message:
'sociodemographic_data' is missing ids listed in 'accessibility_data', which may produce NAs in the final output. 
```

and

```
R> fgt_poverty( 
           access, 
           opportunity = "jobs", 
           sociodemographic_data = blacks, 
           population = "population",
           poverty_line = 95368 
         )                           
   FGT0 FGT1 FGT2
1:   NA   NA   NA
Warning message:
'sociodemographic_data' is missing ids listed in 'accessibility_data', which may produce NAs in the final output. 
```

What do you think?

**Comment by rafapereirabr** [comment]
it's a good compromise.
