### ISSUE TITLE
Theil index, socioeconomic_groups should be optional

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/accessibility#38]
In `theil_index()`, the `socioeconomic_groups` parameter should be optional. Sometimes, users just want to measure the total inequality withou necessarily looking at inequalities between and within particular groups.

My suggestion is that when the user passes `socioeconomic_groups = NULL`, then the `decomposed_theil_t` element of the output should come empty.

**Comment by dhersz** [comment]
Done in https://github.com/ipeaGIT/accessibility/commit/6df39d223f6c9a3d1f3e662466edb4da9e3f6f9f.
