### ISSUE TITLE
update package description to include measures of access poverty and inequality

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/accessibility#51]

**Comment by dhersz** [comment]
Suggestion:

- A set of fast and convenient functions to help conducting accessibility analyses. These functions help both calculating accessibility levels and assessing accessibility poverty and inequality. The majority of the most commonly used methods both in the academic literature and in practice are covered by the package, including (but not limited to): active and passive cumulative measures, gravity-based and floating catchment areas methods, to calculate accessibility; and the Palma ratio, Gini index and FGT poverty measures, to calculate accessibility inequality/poverty.

**Comment by dhersz** [comment]
I'll also update the readme.

**Comment by rafapereirabr** [comment]
Another suggestion building on your suggestion and the original version:
- A set of fast and convenient functions to help conducting accessibility analyses. Given a pre-computed travel cost matrix and a land use dataset (containing for example the location of jobs, healthcare and population), the package allows one to calculate active and passive accessibility levels using multiple accessibility measures as well as to calculate accessibility poverty and inequality. The package covers several measures of accessibility (such as cumulative opportunities, gravity-based and floating catchment areas methods), as well as inequality (Palma ratio, concentraion and Theil index) and and poverty measures (FGT family).
