### ISSUE TITLE
feature request: logistic-CDF decay function

### ISSUE THREAD

**Issue by botanize** [ipeaGIT/accessibility#52]
I'd love to see parity with the [R5 decay functions](https://docs.conveyal.com/learn-more/decay-functions), it seems like logistic-CDF is the notable exception. I'd be willing to contribute a PR if you're interested.

**Comment by rafapereirabr** [comment]
Indeed, it would be nice to make readly available in {accessibility} the same decay functions implemented in R5 and hence in [{r5r}](https://ipeagit.github.io/r5r/reference/accessibility.html).

These are [the decay functions we currently have built in {accessibility}](https://ipeagit.github.io/accessibility/reference/index.html#decay-functions)

- [decay_binary()](https://ipeagit.github.io/accessibility/reference/decay_binary.html)
- [decay_exponential()](https://ipeagit.github.io/accessibility/reference/decay_exponential.html)
- [decay_linear()](https://ipeagit.github.io/accessibility/reference/decay_linear.html)
- [decay_power()](https://ipeagit.github.io/accessibility/reference/decay_power.html)
- [decay_stepped()](https://ipeagit.github.io/accessibility/reference/decay_stepped.html)

So perhaps the {accessibility} package is only missing a `decay_exponential()` and a `decay_logistic()`. Right?

**Comment by botanize** [comment]
Right, `decay_fixed_exponential()` [fixed-exponential-decay](https://docs.conveyal.com/learn-more/decay-functions#fixed-exponential-decay) and `decay_logistic()` [logistic-cdf](https://docs.conveyal.com/learn-more/decay-functions#logistic-cdf).

**Comment by rafapereirabr** [comment]
Ok. Thanks for confirming that. We won't be able to create those functions in the next few weeks due to other project priorities at the moment. However, feel free to create a pull request proposing these two new functions

**Comment by dhersz** [comment]
Did some adjustments to the function, mostly related to documentation. I noticed that there was a limit of 120 to the standard deviation of the logistic curve, even though nothing really seems to impede one of using such value (I see that this restriction exists in R5's original implementation, but not sure why it exists). I decided to remove this restriction, but would be glad to hear your opinions on it.

Thanks again @botanize for the PR. I will close this issue once version 1.4.0 is on CRAN.

**Comment by rafapereirabr** [comment]
Regarding the removal of the "limit of 120 to the standard deviation of the logistic curve", it's fine with me.

**Comment by botanize** [comment]
It also looks like there's no reason for the `sd` parameter to be strictly positive, when zero it just imitates a step function.

**Comment by dhersz** [comment]
That's a good point.

I just checked and the function works mostly fine with sd = 0. The only problem is when you calculate the weight of a cost that is equal to the cutoff. In such case you have e^(0/0), which is indefinite, and the function returns `NaN`. We could arbitrarily decide if `NaN` should be converted to 0 or 1, but I prefer not to because 1) well, it does introduce some arbitrariness to the result and 2) there's a (small) performance penalty on having to check for a `NaN` after calculating results. Since this is an edge case that is in fact covered by `decay_binary()` and `decay_stepped()`, I don't think we should allow sd = 0.
